Repository MapTextLang/MapTextLang, pull requests merged in 2019-03, with the labels that each got.

#1561 修复超僵能被高爆跟电解除效果
  stripper/ze_ffxii_westersand_v7_z9.cfg
Labels: 已测试可合并

#1564 地图难度较大，增加冰冻数量平衡
  mapcfg/ze_deadcore_v1_3.cfg
Labels: 地图平衡, 需要审核

#1580 减少火瓶数量。关闭僵尸毒
  mapcfg/ze_ffxii_feywood_b6_1k.cfg
Labels: 地图平衡, 需要审核

#1578 更新文件名并增加地图基础时长
  mapcfg/ze_rain_of_time_v331X.cfg
Labels: 需要审核

#1614 测试修正神器拾取test
  stripper/ze_FFVII_Mako_Reactor_v5_3_v5.cfg
Labels: 需要测试

#1616 一天内出现4次左右，上调积分
  mappool/ze_best_korea_v1.cfg
Labels: 需要审核
